'use strict';

const fs = require('node:fs');
const path = require('node:path');

// A drive-letter path with none of the characters that could end a VBScript string, expand an
// environment variable (%), or mean anything to a command line. Checked before anything is generated.
const SAFE_PATH = /^[A-Za-z]:\\[^"%<>|*?\x00-\x1f]*$/;

function checkPath(value, label, extension) {
  const ok =
    typeof value === 'string' &&
    SAFE_PATH.test(value) &&
    !value.split('\\').includes('..') &&
    (!extension || value.toLowerCase().endsWith(extension));
  if (!ok) throw new Error(`${label} must be a plain absolute Windows path${extension ? ` ending in ${extension}` : ''}.`);
  return value;
}

const vbs = (text) => `"${text}"`; // paths never contain a double quote (checked above), so no escaping is needed

/**
 * The hidden launcher: `WScript.Shell.Run` with window style 0 starts node without a console window.
 * It is generated from this fixed template; only the three validated paths are inserted.
 */
function buildLauncher({ nodeExe, script, workDir }) {
  checkPath(nodeExe, 'nodeExe', '.exe');
  checkPath(script, 'script', '.js');
  checkPath(workDir, 'workDir');
  return [
    "' FlashPush launcher. Generated by `node src/cli.js --install-autostart`; remove with --uninstall-autostart.",
    'Set shell = CreateObject("WScript.Shell")',
    `shell.CurrentDirectory = ${vbs(workDir)}`,
    `shell.Run ${vbs(`""${nodeExe}"" ""${script}""`)}, 0, False`,
    '',
  ].join('\r\n');
}

function folders(appData = process.env.APPDATA) {
  if (!appData) throw new Error('APPDATA is not set.');
  const programs = path.join(appData, 'Microsoft', 'Windows', 'Start Menu', 'Programs');
  return {
    startup: path.join(programs, 'Startup', 'FlashPush.vbs'),
    startMenu: path.join(programs, 'FlashPush.vbs'),
  };
}

/** Writes the launcher to the current user's Startup folder (no admin rights) and to the Start Menu. */
function installAutostart({ nodeExe, script, workDir, appData }) {
  const text = buildLauncher({ nodeExe, script, workDir });
  const target = folders(appData);
  // UTF-16 with a byte order mark: WScript reads it correctly even when a path has non-ASCII characters.
  const bytes = Buffer.concat([Buffer.from([0xff, 0xfe]), Buffer.from(text, 'utf16le')]);
  for (const file of Object.values(target)) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, bytes);
  }
  return target;
}

function uninstallAutostart({ appData } = {}) {
  for (const file of Object.values(folders(appData))) fs.rmSync(file, { force: true });
}

function autostartStatus({ appData } = {}) {
  const target = folders(appData);
  return { enabled: fs.existsSync(target.startup), startMenu: fs.existsSync(target.startMenu) };
}

module.exports = { buildLauncher, installAutostart, uninstallAutostart, autostartStatus };
